spring:
  profiles:
    active: @profileActive@
  datasource:
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      #配置初始化大小、最小、最大
      initialSize: 3
      minIdle: 1
      maxActive: 20
      #配置获取连接等待超时的时间
      maxWait: 6000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小如果用Oracle，
      #则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      #配置监控统计拦截的filters
      filters: stat,wall
      filter:
        commons-log:
          statement-executable-sql-log-enable: true
  resources:
    static-locations: classpath:/static/
  aop:
    proxy-target-class: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.enable_lazy_load_no_trans: true
  data:
    redis:
      repositories:
        enabled: false
server:
  tomcat:
      uri-encoding: utf-8
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug
permission:
  base-package: com.am.server.api
  enable-super-user: true
  username: 88489527
  password: ODg0ODk1Mjc=
  login-api: /api/admin/login
