spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #基本属性 url、user、password
#    url: jdbc:mysql://localhost:3306/am-server?characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:log4jdbc:mysql://localhost:3306/am-server?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: rxf
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    timeout: 1s
    lettuce:
      shutdown-timeout: 5s
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 8
server:
  port: 9527
logging:
  level:
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
local:
  file:
    file-path: D://file/
    uri: /file
    request-url: http://localhost:${server.port}
