spring:
  datasource:
    #基本属性 url、user、password
    url: jdbc:mysql://mariadb:3306/am-pro?characterEncoding=utf-8&serverTimezone=UTC
    username: ruanxuefeng
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: redis
    port: 6479
    password: r19931229.
    timeout: 1s
    database: 1
    lettuce:
      shutdown-timeout: 5s
      pool:
        max-wait: 2s
        max-idle: 20
        min-idle: 1
        max-active: 8
server:
  port: 9527
local:
  file:
    file-path: /home/file/
    uri: /file
    request-url: http://am-server.ruanxuefeng.xyz
