spring:
  datasource:
    druid:
      #基本属性 url、user、password
      url: jdbc:mysql://localhost:3306/am-server?characterEncoding=utf-8&serverTimezone=UTC
      username: rxf
      #java -cp druid-1.1.9.jar com.alibaba.druid.filter.config.ConfigTools you_password 加密密码命令
      #生成public-key和加密后的密码
      password: Fmoe1KUzWjAtZTc3Tw+YzOkEv69c3XKJ0pJ3SaYsWd6W1gwQAItFr2g4bwtpTNZiAfxQkDfO0LikS64Z6KiCVQ==
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filters: stat,wall,slf4j
      filter:
        config:
          enabled: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: true
          statement-executable-sql-log-enable: false
          statement-log-error-enabled: true
          result-set-log-enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    timeout: 1s
    lettuce:
      shutdown-timeout: 5s
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 8
server:
  port: 9527
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJV4C7Im0QAvKYjjjvGYLR+F28dqngB6gURUn3KttmGzP1P7t+fGg7XuYGf++73s+lyu29mQ0jAXELGdVrpuFjUCAwEAAQ==
logging:
  level:
    druid:
      sql: debug
local:
  file:
    file-path: D://file/
    uri: /file
    request-url: http://localhost:${server.port}
